# -*- coding: utf-8 -*-
"""Capstone_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/syedfaizanahmed/Coursera_Capstone/blob/main/Capstone_Project.ipynb

This repository is mainly for Capstone project for Data Science capstone project.
"""

import numpy as np
import pandas as pd

print('Hello capstone project course!')

